"""
verse_gen_checkpoint — UEFN Toolbelt Community Plugin
======================================================
Generates a complete Verse checkpoint/progression system stub.

Outputs a creative_device with:
  • @editable array of checkpoint trigger devices
  • Sequential activation — only the next checkpoint is active at a time
  • Per-player progress tracking via a persistent map
  • Win condition when all checkpoints are hit
  • Optional reset on player elimination

Use case: racing maps, tutorial maps, obstacle courses, sequential zone captures.

Author: Ocean Bennett (https://github.com/undergroundrap)
Version: 1.0.0
License: AGPL-3.0
"""

MIN_TOOLBELT_VERSION = "1.9.0"

import unreal
from UEFN_Toolbelt.registry import register_tool


@register_tool(
    name="verse_gen_checkpoint",
    category="Community",
    description="Generate a Verse checkpoint/progression system — sequential triggers, "
                "per-player progress, win condition. For racing, tutorial, and obstacle maps.",
    tags=["verse", "codegen", "checkpoint", "progression", "racing", "community"],
)
def verse_gen_checkpoint(device_name: str = "CheckpointManager",
                          checkpoint_count: int = 5,
                          reset_on_elim: bool = True,
                          write_to_snippets: bool = True,
                          **kwargs) -> dict:
    import os

    # Build @editable checkpoint declarations
    checkpoint_decls = "\n".join(
        f"    @editable Checkpoint{i+1} : trigger_device = trigger_device{{}}"
        for i in range(checkpoint_count)
    )

    # Build subscription calls in OnBegin
    subscribe_lines = "\n".join(
        f"        Checkpoint{i+1}.TriggeredEvent.Subscribe(OnCheckpoint{i+1}Reached)"
        for i in range(checkpoint_count)
    )

    # Build handler stubs
    handler_stubs = "\n\n".join(
        f"    OnCheckpoint{i+1}Reached(Agent : agent) : void =\n"
        f"        if (Player := player[Agent], Progress := PlayerProgress[Player]):\n"
        f"            if (Progress = {i}):\n"
        f"                set PlayerProgress[Player] = {i+1}\n"
        f"                if ({i+1} = {checkpoint_count}):\n"
        f"                    OnAllCheckpointsComplete(Player)\n"
        f"                else:\n"
        f"                    Checkpoint{i+2}.Activate(Agent)"
        for i in range(checkpoint_count)
    )

    elim_block = ""
    if reset_on_elim:
        elim_block = """
    OnPlayerEliminated(Result : elimination_result) : void =
        if (Player := player[Result.EliminatedAgent]):
            set PlayerProgress[Player] = 0
            Checkpoint1.Activate(Result.EliminatedAgent)
"""

    verse_code = f"""using {{ /Fortnite.com/Devices }}
using {{ /Fortnite.com/Characters }}
using {{ /Fortnite.com/Playspaces }}
using {{ /Verse.org/Simulation }}

# Generated by verse_gen_checkpoint — UEFN Toolbelt Community Plugin
# Checkpoint count: {checkpoint_count}  |  Reset on elimination: {reset_on_elim}
# Place this device in your level, wire @editable refs in the Properties panel.

{device_name} := class(creative_device):

    # ── Checkpoint devices (wire these in the Properties panel) ───────────
{checkpoint_decls}

    # ── Per-player progress: value = next checkpoint index expected (0-based) ──
    var PlayerProgress : [player]int = map{{}}

    OnBegin<override>()<suspends> : void =
        # Activate only the first checkpoint at start
        Gameplay := GetPlayspace().GetGameplay()
{subscribe_lines}
        {"Gameplay.PlayerEliminatedEvent.Subscribe(OnPlayerEliminated)" if reset_on_elim else ""}

    # ── Checkpoint handlers ────────────────────────────────────────────────
{handler_stubs}
{elim_block}
    OnAllCheckpointsComplete(Player : player) : void =
        # TODO: award win, show UI, trigger end-game device
        Print("Player completed all {checkpoint_count} checkpoints!")
"""

    filename = f"{device_name}.verse"
    output_path = ""

    if write_to_snippets:
        try:
            saved_dir = unreal.Paths.project_saved_dir().replace("\\", "/").rstrip("/")
            snippets_dir = f"{saved_dir}/UEFN_Toolbelt/snippets/custom"
            os.makedirs(snippets_dir, exist_ok=True)
            output_path = f"{snippets_dir}/{filename}"
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(verse_code)
            unreal.log(f"[verse_gen_checkpoint] Written to {output_path}")
        except Exception as e:
            unreal.log_warning(f"[verse_gen_checkpoint] Could not write file: {e}")

    unreal.log(f"\n{'='*60}\n{verse_code}\n{'='*60}")

    return {
        "status": "ok",
        "device_name": device_name,
        "checkpoint_count": checkpoint_count,
        "filename": filename,
        "output_path": output_path,
        "verse_code": verse_code,
    }
