"""
UEFN TOOLBELT — Tools Package
========================================
Each import here triggers the module's @register_tool decorators, which
automatically adds the tool to the global ToolRegistry.

To add a new tool:
  1. Create tools/my_tool.py with a @register_tool-decorated entry function.
  2. Add:  from . import my_tool    ← right here.
  Done.
"""

from . import (
    activity_log_tools,
    actor_org_tools,
    actor_visibility,
    advanced_alignment,
    animation_tools,
    api_capability_crawler,
    api_explorer,
    arena_generator,
    asset_importer,
    asset_renamer,
    asset_tagger,
    audio_design_tools,
    audio_tools,
    blueprint_tools,
    bulk_operations,
    config_tools,
    cooker_optimizer,
    curve_tools,
    datatable_tools,
    enhanced_input_tools,
    entity_kits,
    epic_mcp_tools,
    foliage_converter,
    foliage_tools,
    geometry_tools,
    integration_test,
    landscape_tools,
    level_health,
    level_snapshot,
    lighting_mastery,
    localization_tools,
    lod_tools,
    material_master,
    mcp_bridge,
    measurement_tools,
    memory_profiler,
    movie_render_tools,
    niagara_tools,
    optimization_tools,
    pcg_tools,
    physics_tools,
    plugin_manager,
    postprocess_tools,
    prefab_migrator,
    prefab_stamp,
    procedural_geometry,
    project_admin,
    project_scaffold,
    project_setup,
    prop_patterns,
    proximity_tools,
    publish_audit,
    reference_auditor,
    screenshot_tools,
    selection_utils,
    sequencer_tools,
    sign_tools,
    sim_device_proxy,
    skeletal_mesh_tools,
    smart_importer,
    smart_organizer,
    sound_asset_tools,
    spline_prop_placer,
    spline_to_verse,
    system_build,
    system_perf,
    text_painter,
    text_voxelizer,
    texture_tools,
    ui_icon_import,
    verse_device_editor,
    verse_device_graph,
    verse_schema,
    verse_snippet_generator,
    verse_templates,
    viewport_tools,
    world_partition_tools,
    zone_tools,
)
