"""
UEFN TOOLBELT — Localization Tools
========================================
Tools for bulk-exporting map text and re-importing translations.
A major pain point for global UEFN maps.
"""

from __future__ import annotations

import json
import csv
import os
from typing import List, Dict, Any

import unreal

from ..core import log_info, log_warning, log_error, with_progress
from ..registry import register_tool

# ─────────────────────────────────────────────────────────────────────────────
#  Configuration
# ─────────────────────────────────────────────────────────────────────────────

EXPORT_DIR = os.path.join(unreal.Paths.project_saved_dir(), "UEFN_Toolbelt", "localization")

# ─────────────────────────────────────────────────────────────────────────────
#  Registered Tools
# ─────────────────────────────────────────────────────────────────────────────

@register_tool(
    name="text_export_manifest",
    category="Localization",
    description="Find all TextRenderActors and translatable devices and export their text to CSV/JSON.",
    tags=["localization", "text", "export", "translate", "list"],
)
def run_text_export_manifest(format: str = "json", **kwargs) -> str:
    """
    Scans the current level for all TextRenderActors and harvests their text.
    Exports to Saved/UEFN_Toolbelt/localization/manifest.[json|csv]
    """
    actor_sub = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    all_actors = actor_sub.get_all_level_actors()
    
    records = []
    
    with with_progress(all_actors, "Harvesting Text...") as bar:
        for actor in bar:
            # 1. Check for TextRenderActor
            if isinstance(actor, unreal.TextRenderActor):
                txt = actor.text_render_component.text
                records.append({
                    "actor_name": actor.get_actor_label(),
                    "actor_path": actor.get_path_name(),
                    "original_text": str(txt),
                    "type": "TextRender"
                })
            
            # 2. Add logic here for custom Verse dev props if they are exposed to Python
            # (Requires checking specific device classes or looking for String properties)

    if not records:
        log_warning("No translatable text found in the current level.")
        return ""

    os.makedirs(EXPORT_DIR, exist_ok=True)
    out_path = os.path.join(EXPORT_DIR, f"manifest.{format}")

    if format.lower() == "csv":
        with open(out_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=["actor_name", "actor_path", "original_text", "type"])
            writer.writeheader()
            writer.writerows(records)
    else:
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(records, f, indent=2)

    log_info(f"✓ Exported {len(records)} strings to {out_path}")
    return out_path


@register_tool(
    name="text_apply_translation",
    category="Localization",
    description="Read a translated JSON manifest and update actors in the level with new strings.",
    tags=["localization", "text", "import", "apply", "translate"],
)
def run_text_apply_translation(manifest_path: str = "", **kwargs) -> bool:
    """
    Reads a JSON manifest (generated by text_export_manifest) and applies strings back to actors.
    The manifest should have an 'actor_path' and a 'translated_text' field for each entry.
    """
    if not manifest_path or not os.path.exists(manifest_path):
        log_error("Invalid manifest path provided.")
        return False

    try:
        with open(manifest_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        log_error(f"Failed to read manifest: {e}")
        return False

    applied_count = 0
    with unreal.ScopedEditorTransaction("Apply Translations"):
        for entry in data:
            path = entry.get("actor_path")
            new_text = entry.get("translated_text") or entry.get("original_text")
            
            if not path or new_text is None:
                continue
                
            actor = unreal.load_asset(path)
            if actor and isinstance(actor, unreal.TextRenderActor):
                actor.text_render_component.set_text(new_text)
                applied_count += 1
            else:
                log_warning(f"Could not find or update actor at {path}")

    log_info(f"✓ Applied {applied_count} translations from manifest.")
    return True
