"""
UEFN TOOLBELT — Verse Simulation Proxies
========================================
Test Verse logic in-editor without full sessions. 
Uses the schema to mirror Verse device APIs.
"""

from __future__ import annotations
import os
import unreal
from ..core import log_info, log_error, undo_transaction, require_selection
from ..registry import register_tool
from .. import schema_utils
from . import verse_schema

def _resolve_verse_class(actor: unreal.Actor) -> str:
    """
    Extract the specific Verse class name from a generic VerseDevice_C.
    e.g. 'hello_world_device' from a DEVICE_UAID_..._C.
    """
    cls = actor.get_class()
    name = cls.get_name()
    path = cls.get_path_name()
    
    # In UEFN, user Verse devices appear as VerseDevice_C or name_UAID..._C
    if "_Verse." in path:
        return path.split(".")[-1]
    
    # Try getting the specific Verse class if it's a VerseDevice instance
    if name == "VerseDevice_C" or "VerseDevice" in name:
        # Check for common Verse internal properties.
        # Quirk #7: get_editor_property raises on Verse-driven properties;
        # use getattr which reflects all Python-accessible attributes.
        for p in ["verse_class", "VerseClass", "ScriptClass"]:
            try:
                v_type = getattr(actor, p, None)
                if v_type:
                    return str(v_type).split(".")[-1]
            except Exception:
                pass
        
        # FINAL FALLBACK: Fuzzy Match based on Actor Label
        # If the user renamed the actor to match their Verse class (default behavior)
        label = actor.get_actor_label()
        normalized = label.lower().replace(" ", "_")
        # Remove common UEFN suffixes
        normalized = normalized.split("_C_")[0].split("_UAID_")[0]
        return normalized

    return name.replace("_C", "")

@register_tool(
    name="sim_generate_proxy",
    category="Simulation",
    description="Generate a Python simulation proxy for a selected Verse device.",
    tags=["sim", "verse", "proxy", "automation"],
)
def run_generate_proxy(**kwargs) -> dict:
    actors = require_selection(min_count=1)
    if not actors:
        return {"status": "error", "message": "No actors selected."}

    actor = actors[0]
    cls_raw = actor.get_class().get_name()
    v_cls = _resolve_verse_class(actor)
    
    log_info(f"Analyzing {actor.get_actor_label()} (Class: {v_cls})")

    # 1. Try Dynamic Verse Schema (Project-specific)
    info = verse_schema._parser.get_schema(v_cls)
    
    # 2. Try Static Reference Schema (Engine-standard)
    if not info:
        info = schema_utils.get_class_info(v_cls)
        
    if not info:
        log_error(f"Class '{v_cls}' not found in any schema.")
        log_info("Tip: Ensure your Verse code is compiled and you've run 'Sync Level Schema'.")
        return

    props   = info.get("properties", {})
    methods = info.get("methods", []) or info.get("functions", [])
    events  = info.get("events", [])

    log_info(f"Generating proxy for '{v_cls}' — {len(props)} props, {len(methods)} methods, {len(events)} events…")

    cls_title = "".join(w.capitalize() for w in v_cls.replace("-", "_").split("_"))

    lines = [
        f"# Auto-generated by UEFN Toolbelt — sim_generate_proxy",
        f"# Verse class : {v_cls}",
        f"# Actor label : {actor.get_actor_label()}",
        f"# Raw class   : {cls_raw}",
        f"# Usage:",
        f"#   import UEFN_Toolbelt as tb",
        f"#   from {v_cls}_proxy import {cls_title}Proxy",
        f"#   sub = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)",
        f"#   actor = next(a for a in sub.get_all_level_actors()",
        f"#                if a.get_actor_label() == '{actor.get_actor_label()}')",
        f"#   dev = {cls_title}Proxy(actor)",
        f"import unreal",
        f"",
        f"class {cls_title}Proxy:",
        f'    """Python simulation proxy for the Verse device \'{v_cls}\'.',
        f"    Wraps an unreal.Actor so editor tools can read and write its",
        f"    properties using typed Python instead of raw string APIs.",
        f'    """',
        f"",
        f"    def __init__(self, actor: unreal.Actor) -> None:",
        f"        self._actor = actor",
        f"        self.verse_class = {v_cls!r}",
        f"",
    ]

    # ── Property accessors ─────────────────────────────────────────────────
    if props:
        lines.append("    # ── Editable Properties ─────────────────────────────────────────────")
        for prop_name, meta in props.items():
            py_name   = prop_name[0].lower() + prop_name[1:]  # bIsEnabled → bIsEnabled (keep as-is)
            prop_type = meta.get("type", "Any") if isinstance(meta, dict) else "Any"
            readable  = meta.get("readable", True) if isinstance(meta, dict) else True

            lines += [
                f"    @property",
                f"    def {py_name}(self):",
                f"        return getattr(self._actor, {prop_name!r}, None)",
                f"",
            ]
            if readable:
                lines += [
                    f"    @{py_name}.setter",
                    f"    def {py_name}(self, value) -> None:",
                    f"        try:",
                    f"            self._actor.set_editor_property({prop_name!r}, value)",
                    f"        except Exception:",
                    f"            setattr(self._actor, {prop_name!r}, value)",
                    f"",
                ]

    # ── Method stubs ────────────────────────────────────────────────────────
    if methods:
        lines.append("    # ── Methods ─────────────────────────────────────────────────────────")
        for method in methods:
            py_method = method if isinstance(method, str) else method.get("name", "unknown")
            lines += [
                f"    def {py_method}(self, *args, **kwargs):",
                f"        if hasattr(self._actor, {py_method!r}):",
                f"            return getattr(self._actor, {py_method!r})(*args, **kwargs)",
                f"",
            ]

    # ── Event subscriptions ─────────────────────────────────────────────────
    if events:
        lines.append("    # ── Events ──────────────────────────────────────────────────────────")
        for event in events:
            ev_name = event if isinstance(event, str) else event.get("name", "unknown")
            lines += [
                f"    def subscribe_{ev_name.lower()}(self, handler) -> None:",
                f"        evt = getattr(self._actor, {ev_name!r}, None)",
                f"        if evt and hasattr(evt, 'Subscribe'):",
                f"            evt.Subscribe(handler)",
                f"",
            ]

    # ── Inspect helper ──────────────────────────────────────────────────────
    prop_keys = list(props.keys())
    lines += [
        "    # ── Dev Helper ──────────────────────────────────────────────────────────",
        "    def inspect(self) -> dict:",
        '        """Return a snapshot of all proxy-tracked properties."""',
        f"        keys = {prop_keys!r}",
        "        return {k: getattr(self._actor, k, None) for k in keys}",
        "",
    ]

    code = "\n".join(lines)

    out_dir  = os.path.join(unreal.Paths.project_saved_dir(), "UEFN_Toolbelt", "proxies")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, f"{v_cls}_proxy.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(code)

    log_info(f"Proxy written → {out_path}")
    log_info(f"  Class : {cls_title}Proxy  |  {len(props)} props · {len(methods)} methods · {len(events)} events")
    return {
        "status": "ok",
        "class": cls_title + "Proxy",
        "path": out_path,
        "props": len(props),
        "methods": len(methods),
        "events": len(events),
    }


@register_tool(
    name="sim_trigger_method",
    category="Simulation",
    description="Trigger a discoverable method on a Verse device via the Python API.",
    tags=["sim", "verse", "trigger", "method"],
)
def run_trigger_method(method_name: str = "", **kwargs) -> dict:
    """
    Simulates calling a Verse function by executing its Python equivalent.
    """
    actors = require_selection(min_count=1)
    if not actors:
        return {"status": "error", "message": "No actors selected."}
    if not method_name:
        return {"status": "error", "message": "method_name is required."}

    actor = actors[0]
    if hasattr(actor, method_name):
        log_info(f"Simulating: {actor.get_actor_label()}.{method_name}()")
        with undo_transaction(f"Sim: Trigger {method_name}"):
            try:
                getattr(actor, method_name)()
                return {"status": "ok", "actor": actor.get_actor_label(), "method": method_name}
            except Exception as e:
                log_error(f"Failed to trigger {method_name}: {e}")
                return {"status": "error", "message": str(e)}
    else:
        log_error(f"Method '{method_name}' not found on this actor.")
        return {"status": "error", "message": f"Method '{method_name}' not found on {actor.get_actor_label()}"}
