"""
UEFN TOOLBELT — Quick Verse Snippet Generator
========================================
Context-aware Verse boilerplate from your current level selection.
Stop hand-typing device declarations and event hooks — generate them
from what's actually in your level.

FEATURES:
  • Inspect selected actors → generate typed Verse device declarations
  • Generate a full verse_devices.verse device module skeleton
  • Generate event handler stubs for common device events
  • Generate OnBegin / Tick / player-loop boilerplate
  • Generate prop spawn / despawn patterns
  • Generate scoring / elimination tracker skeleton
  • Output to Saved/UEFN_Toolbelt/snippets/ as .verse files
  • Copy-to-clipboard helper (Windows only, graceful fallback)
  • All snippets heavily commented for learning

USAGE:
    import UEFN_Toolbelt as tb

    # Generate device declarations from selection
    tb.run("verse_gen_device_declarations")

    # Generate a full game device skeleton
    tb.run("verse_gen_game_skeleton", device_name="MyGameManager")

    # Generate scoring tracker
    tb.run("verse_gen_scoring_tracker", max_score=10)

    # Generate elimination event handler
    tb.run("verse_gen_elimination_handler")

    # List all available snippets
    tb.run("verse_list_snippets")
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import List, Optional

import unreal

from ..core import (
    get_selected_actors, log_info, log_warning, log_error,
)
from ..registry import register_tool

# ─────────────────────────────────────────────────────────────────────────────
#  Output directory
# ─────────────────────────────────────────────────────────────────────────────

SNIPPETS_DIR = os.path.join(
    unreal.Paths.project_saved_dir(), "UEFN_Toolbelt", "snippets"
)

# Subcategory folders — every snippet goes into one of these
SUBCAT_GAME_SYSTEMS  = "game_systems"    # game manager, round logic, scoring
SUBCAT_DEVICE_WIRING = "device_wiring"  # device declarations, prop spawner
SUBCAT_SPLINE_TOOLS  = "spline_tools"   # spline → Verse converters
SUBCAT_CUSTOM        = "custom"         # user-generated / Claude-generated

# ─────────────────────────────────────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _write_snippet(filename: str, content: str, subcategory: str = SUBCAT_CUSTOM) -> str:
    """Write snippet to disk under the appropriate subcategory folder."""
    dest = os.path.join(SNIPPETS_DIR, subcategory)
    os.makedirs(dest, exist_ok=True)
    path = os.path.join(dest, filename)
    with open(path, "w") as f:
        f.write(content)
    return path


def _try_clipboard(text: str) -> None:
    """Copy text to Windows clipboard if available."""
    try:
        import subprocess
        subprocess.run(["clip"], input=text.encode("utf-8"), check=True)
        log_info("  Snippet copied to clipboard.")
    except Exception:
        pass  # Not on Windows, or clip not available


def _actor_to_verse_device_type(actor: unreal.Actor) -> str:
    """
    Map a UE actor class name to the nearest Verse device type.
    These are approximations — adjust to match your exact UEFN SDK version.
    """
    class_name = actor.get_class().get_name().lower()
    mapping = {
        "trigger":       "trigger_device",
        "timer":         "timer_device",
        "spawnpad":      "player_spawner_device",
        "button":        "button_device",
        "chest":         "chest_device",
        "beacon":        "capture_area_device",
        "zone":          "mutator_zone_device",
        "tracker":       "tracker_device",
        "scoreboard":    "scoreboard_device",
        "barrier":       "barrier_device",
        "ammo":          "item_spawner_device",
        "vehicle":       "vehicle_spawner_device",
        "elimination":   "elimination_manager_device",
    }
    for key, verse_type in mapping.items():
        if key in class_name:
            return verse_type
    return "creative_device"  # fallback base type


def _safe_ident(label: str) -> str:
    """Convert actor label to a valid Verse identifier."""
    result = label.strip().replace(" ", "_").replace("-", "_")
    result = "".join(c if c.isalnum() or c == "_" else "_" for c in result)
    if result and result[0].isdigit():
        result = "d_" + result
    return result.lower()


# ─────────────────────────────────────────────────────────────────────────────
#  Verse Snippet Templates
# ─────────────────────────────────────────────────────────────────────────────

_HEADER = """\
# ============================================================
# Generated by UEFN Toolbelt — Verse Snippet Generator
# {timestamp}
# ============================================================
using { /Fortnite.com/Devices }
using {{ /Verse.org/Simulation }}
using {{ /UnrealEngine.com/Temporary/Diagnostics }}

"""

_GAME_SKELETON = '''\
using {{ /Fortnite.com/Devices }}
using {{ /Fortnite.com/Game }}
using {{ /Fortnite.com/Teams }}
using {{ /Verse.org/Simulation }}
using {{ /UnrealEngine.com/Temporary/Diagnostics }}

# ──────────────────────────────────────────────────────────────
# {device_name}
# Main game manager device — attach this to a Creative Device
# Blueprint in UEFN and configure sub-devices in the Details panel.
# ──────────────────────────────────────────────────────────────
{device_name} := class(creative_device):

    # ── Sub-device references (wire these in the Blueprint Details) ──────
    @editable  SpawnPad1    : player_spawner_device = player_spawner_device{{}}
    @editable  SpawnPad2    : player_spawner_device = player_spawner_device{{}}
    @editable  Scoreboard   : scoreboard_device     = scoreboard_device{{}}
    @editable  EndGameTimer : timer_device           = timer_device{{}}

    # ── Configurable parameters ─────────────────────────────────────────
    @editable  MaxScore     : int = 10
    @editable  RoundTimeSec : float = 300.0

    # ── Internal state ───────────────────────────────────────────────────
    var CurrentScore<private> : int = 0

    # ── Lifecycle ────────────────────────────────────────────────────────

    # Called once when the game starts.
    OnBegin<override>()<suspends> : void =
        Print("{{device_name}}: OnBegin")
        _SetupEvents()
        _StartRound()

    # Wire up all device event handlers here.
    _SetupEvents()<private>() : void =
        EndGameTimer.SuccessEvent.Subscribe(OnTimerExpired)
        # Add more event subscriptions here.

    # Start a new round — spawn players, reset state, start timer.
    _StartRound<private>()<suspends> : void =
        set CurrentScore = 0
        SpawnPad1.Enable()
        SpawnPad2.Enable()
        EndGameTimer.Start()
        Print("{{device_name}}: Round started")

    # Called when the round timer expires.
    OnTimerExpired<private>(TimerDevice : timer_device) : void =
        Print("{{device_name}}: Timer expired — ending round")
        _EndRound()

    # Clean up and signal game over.
    _EndRound<private>() : void =
        SpawnPad1.Disable()
        SpawnPad2.Disable()
        EndGameTimer.Stop()
        Scoreboard.ShowScoreboard()
        Print("{{device_name}}: Round ended. Final score: {{CurrentScore}}")
'''

_ELIMINATION_HANDLER = '''\
using {{ /Fortnite.com/Devices }}
using {{ /Fortnite.com/Characters }}
using {{ /Verse.org/Simulation }}
using {{ /UnrealEngine.com/Temporary/Diagnostics }}

# Elimination event handler — tracks kills and updates score.
elimination_tracker := class(creative_device):

    @editable  ScorePerKill : int = 1
    @editable  Scoreboard   : scoreboard_device = scoreboard_device{{}}

    var TotalEliminations<private> : int = 0

    OnBegin<override>()<suspends> : void =
        # Fort characters expose an EliminatedEvent on agents.
        # Subscribe via your elimination_manager_device:
        # EliminationManager.EliminationEvent.Subscribe(OnElimination)
        Print("elimination_tracker: Ready")

    # Called when any player is eliminated.
    OnElimination<private>(Result : elimination_result) : void =
        set TotalEliminations += 1
        EliminatorAgent := Result.EliminatingAgent
        if (Player := player[EliminatorAgent]):
            # Update the scoreboard for the eliminating player
            Scoreboard.SetScoreboardScore(Player, TotalEliminations * ScorePerKill)
            Print("Elimination #{TotalEliminations} — updating score")
'''

_SCORING_TRACKER = '''\
using {{ /Fortnite.com/Devices }}
using {{ /Verse.org/Simulation }}
using {{ /UnrealEngine.com/Temporary/Diagnostics }}

# Scoring tracker — grants points when players enter a zone.
scoring_tracker := class(creative_device):

    @editable  ScoreZone    : mutator_zone_device  = mutator_zone_device{{}}
    @editable  Scoreboard   : scoreboard_device    = scoreboard_device{{}}
    @editable  PointsPerTick: int                  = 1
    @editable  MaxScore     : int                  = {max_score}

    var PlayerScores<private> : [player]int = map{{}}

    OnBegin<override>()<suspends> : void =
        ScoreZone.AgentEntersZoneEvent.Subscribe(OnAgentEnter)
        Print("scoring_tracker: Active — max score {{MaxScore}}")

    OnAgentEnter<private>(Agent : agent) : void =
        if (P := player[Agent]):
            CurrentScore := if (S := PlayerScores[P]) then S else 0
            NewScore      := CurrentScore + PointsPerTick
            set PlayerScores[P] = NewScore
            Scoreboard.SetScoreboardScore(P, NewScore)
            if (NewScore >= MaxScore):
                Print("Player reached max score!")
                # Trigger win condition here
'''

_PROP_SPAWN = '''\
using {{ /Fortnite.com/Devices }}
using {{ /Verse.org/Simulation }}
using {{ /UnrealEngine.com/Temporary/Diagnostics }}

# Prop spawn / despawn pattern with trigger.
prop_spawner_controller := class(creative_device):

    @editable  SpawnTrigger  : trigger_device      = trigger_device{{}}
    @editable  DespawnTrigger: trigger_device      = trigger_device{{}}
    @editable  PropSpawner   : item_spawner_device = item_spawner_device{{}}
    @editable  SpawnDelay    : float               = 0.5

    OnBegin<override>()<suspends> : void =
        SpawnTrigger.TriggeredEvent.Subscribe(OnSpawnTriggered)
        DespawnTrigger.TriggeredEvent.Subscribe(OnDespawnTriggered)

    OnSpawnTriggered<private>(Agent : ?agent) : void =
        Sleep(SpawnDelay)
        PropSpawner.Enable()
        Print("Prop spawner enabled")

    OnDespawnTriggered<private>(Agent : ?agent) : void =
        PropSpawner.Disable()
        Print("Prop spawner disabled")
'''


# ─────────────────────────────────────────────────────────────────────────────
#  Registered Tools
# ─────────────────────────────────────────────────────────────────────────────

def _find_uefn_project_root() -> str:
    """
    Walk up from this file's location to find the UEFN project root.
    The Toolbelt lives at [ProjectRoot]/Content/Python/UEFN_Toolbelt/
    so we walk up until we find the 'Content' directory, then return its parent.
    This is the only reliable way to find the user project root in UEFN —
    unreal.Paths.project_dir() returns the FortniteGame engine directory, not
    the user project directory.
    """
    curr = os.path.abspath(__file__)
    while True:
        parent = os.path.dirname(curr)
        if parent == curr:
            # Reached filesystem root without finding Content — fall back
            return unreal.Paths.project_saved_dir()
        if os.path.basename(curr) == "Content":
            return parent
        curr = parent


def _find_verse_project_dir() -> str:
    """
    Auto-detect the Verse source directory for the current UEFN project.

    Search order:
    1. config verse.project_path (user override — most reliable)
    2. [ProjectRoot]/Verse/  (standard UEFN layout)
    3. [ProjectRoot]/*.verse/ (Epic's Verse package folder naming)
    4. Falls back to Saved/UEFN_Toolbelt/snippets/custom/ with a clear warning

    NOTE: Never uses unreal.Paths.project_dir() — in UEFN that resolves to
    the FortniteGame engine directory, not the user's project directory.
    """
    from ..core.config import get_config
    cfg = get_config()
    user_path = cfg.get("verse.project_path", "")
    if user_path and os.path.isdir(user_path):
        return user_path

    project_root = _find_uefn_project_root()

    # Standard layout
    standard = os.path.join(project_root, "Verse")
    if os.path.isdir(standard):
        return standard

    # Epic's .verse package folder naming
    for entry in os.listdir(project_root):
        full = os.path.join(project_root, entry)
        if entry.endswith(".verse") and os.path.isdir(full):
            return full

    # Fallback — create standard Verse dir in project root
    os.makedirs(standard, exist_ok=True)
    return standard


@register_tool(
    name="verse_find_project_path",
    category="Verse Helpers",
    description="Auto-detect and return the Verse source directory for the current UEFN project.",
    tags=["verse", "path", "project", "config"],
)
def run_verse_find_project_path(**kwargs) -> dict:
    """
    Returns the path Claude should use when writing .verse files for this project.
    Set config verse.project_path to override auto-detection.

    Returns:
        {"status": "ok", "path": str, "source": "config"|"standard"|"package"|"created"}
    """
    from ..core.config import get_config
    cfg = get_config()
    user_path = cfg.get("verse.project_path", "")
    if user_path and os.path.isdir(user_path):
        log_info(f"Verse project path (from config): {user_path}")
        return {"status": "ok", "path": user_path, "source": "config"}

    project_root = _find_uefn_project_root()
    standard = os.path.join(project_root, "Verse")
    if os.path.isdir(standard):
        log_info(f"Verse project path (standard): {standard}")
        return {"status": "ok", "path": standard, "source": "standard"}

    for entry in os.listdir(project_root):
        full = os.path.join(project_root, entry)
        if entry.endswith(".verse") and os.path.isdir(full):
            log_info(f"Verse project path (package): {full}")
            return {"status": "ok", "path": full, "source": "package"}

    os.makedirs(standard, exist_ok=True)
    log_info(f"Verse project path (created): {standard}")
    return {"status": "ok", "path": standard, "source": "created"}


@register_tool(
    name="verse_write_file",
    category="Verse Helpers",
    description=(
        "Write Verse code directly into the project's Verse source directory — "
        "the file is immediately visible to UEFN's compiler. "
        "The AI deployment layer: Claude generates Verse, this tool places it."
    ),
    tags=["verse", "write", "file", "deploy", "ai", "automation", "compile"],
    example='tb.run("verse_write_file", filename="game_manager.verse", content=verse_code, overwrite=True)',
)
def run_verse_write_file(
    filename: str = "",
    content: str = "",
    subdir: str = "",
    overwrite: bool = False,
    **kwargs,
) -> dict:
    """
    Write ``content`` to ``filename`` inside the project's Verse source directory.
    After writing, open UEFN and click 'Compile Verse' (or run system_build_verse).

    Args:
        filename:  The .verse filename (e.g. "game_manager.verse").
                   A .verse extension is added automatically if missing.
        content:   The full Verse source code to write.
        subdir:    Optional subdirectory inside the Verse project root.
        overwrite: If False (default), raises an error if the file already exists
                   so Claude never silently stomps existing work.

    Returns:
        {
          "status": "ok",
          "path": str,           # absolute path of the written file
          "bytes": int,
          "next_step": str       # instruction for what to do next
        }

    Example:
        tb.run("verse_write_file",
               filename="game_manager.verse",
               content="game_manager := class(creative_device): ...",
               overwrite=True)
    """
    if not filename:
        return {"status": "error", "message": "filename is required."}
    if not content:
        return {"status": "error", "message": "content is required."}

    if not filename.endswith(".verse"):
        filename += ".verse"

    verse_root = _find_verse_project_dir()
    dest_dir = os.path.join(verse_root, subdir) if subdir else verse_root
    os.makedirs(dest_dir, exist_ok=True)
    out_path = os.path.join(dest_dir, filename)

    if os.path.exists(out_path) and not overwrite:
        return {
            "status": "error",
            "message": f"File already exists: {out_path}. Pass overwrite=True to replace.",
            "path": out_path,
        }

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    log_info(f"[verse_write_file] ✓ Written: {out_path} ({len(content)} bytes)")
    return {
        "status": "ok",
        "path": out_path,
        "bytes": len(content),
        "next_step": "Click 'Compile Verse' in UEFN, or run tb.run('system_build_verse') to compile and check for errors.",
    }


@register_tool(
    name="verse_gen_custom",
    category="Verse Helpers",
    description=(
        "Write a custom Verse snippet to disk. Pass spec-accurate code generated "
        "by Claude after querying verse_book_search / verse_book_chapter."
    ),
    tags=["verse", "snippet", "custom", "generate", "ai", "spec"],
)
def run_gen_custom(
    filename: str = "custom_snippet.verse",
    code: str = "",
    description: str = "",
    **kwargs,
) -> dict:
    """
    Write arbitrary Verse code to the snippets folder.
    Intended to be called by Claude after consulting the verse-book spec
    via verse_book_search / verse_book_chapter MCP tools.

    Args:
        filename:    Output filename (e.g. 'my_device.verse').
        code:        The Verse code to write (spec-verified by Claude).
        description: Human-readable description added as a header comment.
    """
    if not code:
        log_warning("verse_gen_custom: no code provided.")
        return {"path": "", "bytes": 0}

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = (
        f"# ============================================================\n"
        f"# Generated by UEFN Toolbelt — verse_gen_custom\n"
        f"# {timestamp}\n"
    )
    if description:
        header += f"# {description}\n"
    header += "# Spec: https://github.com/verselang/book\n"
    header += "# ============================================================\n\n"

    content = header + code
    if not filename.endswith(".verse"):
        filename += ".verse"
    path = _write_snippet(filename, content, SUBCAT_CUSTOM)
    _try_clipboard(content)
    log_info(f"Custom Verse snippet written → {path}")
    return {"path": path, "bytes": len(content)}


@register_tool(
    name="verse_list_snippets",
    category="Verse Helpers",
    description="List all generated snippet files in the Saved/UEFN_Toolbelt/snippets/ folder.",
    tags=["verse", "snippet", "list"],
)
def run_list_snippets(**kwargs) -> dict:
    """
    Returns:
        dict: {"status", "count", "snippets": [{"subcat", "filename", "size_bytes"}]}
    """
    if not os.path.isdir(SNIPPETS_DIR):
        log_info("No snippets generated yet. Run a verse_gen_* tool first.")
        return {"status": "ok", "count": 0, "snippets": []}
    lines = [f"\n=== Verse Snippet Library ({SNIPPETS_DIR}) ==="]
    all_snippets = []
    for subcat in sorted(os.listdir(SNIPPETS_DIR)):
        subdir = os.path.join(SNIPPETS_DIR, subcat)
        if not os.path.isdir(subdir):
            continue
        files = [f for f in sorted(os.listdir(subdir)) if f.endswith(".verse")]
        if not files:
            continue
        lines.append(f"\n  [{subcat}]")
        for f in files:
            size = os.path.getsize(os.path.join(subdir, f))
            lines.append(f"    {f:44s}  {size:>6} bytes")
            all_snippets.append({"subcat": subcat, "filename": f, "size_bytes": size})
    lines.append(f"\n  {len(all_snippets)} snippet(s) total")
    log_info("\n".join(lines))
    return {"status": "ok", "count": len(all_snippets), "snippets": all_snippets}


@register_tool(
    name="verse_open_snippets_folder",
    category="Verse Helpers",
    description="Open the Verse snippet library folder in Windows Explorer.",
    tags=["verse", "snippet", "folder", "open", "explore"],
)
def run_open_snippets_folder(**kwargs) -> dict:
    """
    Returns:
        dict: {"status", "path"}
    """
    os.makedirs(SNIPPETS_DIR, exist_ok=True)
    import subprocess
    subprocess.Popen(["explorer", os.path.normpath(SNIPPETS_DIR)])
    log_info(f"Opened snippet library: {SNIPPETS_DIR}")
    return {"status": "ok", "path": SNIPPETS_DIR}


@register_tool(
    name="verse_gen_device_declarations",
    category="Verse Helpers",
    description="Generate Verse @editable device declarations from the current selection.",
    tags=["verse", "snippet", "device", "generate", "boilerplate"],
)
def run_gen_device_declarations(**kwargs) -> dict:
    """
    Inspect the selected actors and generate typed @editable Verse declarations
    ready to paste into a creative_device class body.

    Returns:
        dict: {"status", "path", "code", "device_count"}
    """
    actors = get_selected_actors()
    if not actors:
        log_warning("Select Verse device actors in the viewport first.")
        return {"status": "error", "path": "", "code": "", "device_count": 0}

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"# Generated by UEFN Toolbelt — {timestamp}",
        "# Paste these into your creative_device class body:\n",
    ]

    for actor in actors:
        ident      = _safe_ident(actor.get_actor_label())
        verse_type = _actor_to_verse_device_type(actor)
        label      = actor.get_actor_label()
        loc        = actor.get_actor_location()
        lines.append(
            f"    # Actor: '{label}'  @ ({loc.x:.0f}, {loc.y:.0f}, {loc.z:.0f})"
        )
        lines.append(
            f"    @editable  {ident:<24s}: {verse_type} = {verse_type}{{}}"
        )
        lines.append("")

    snippet = "\n".join(lines)
    path = _write_snippet("device_declarations.verse", snippet, SUBCAT_DEVICE_WIRING)
    _try_clipboard(snippet)
    log_info(f"Device declarations generated → {path}\n\n{snippet}")
    return {"status": "ok", "path": path, "code": snippet, "device_count": len(actors)}


@register_tool(
    name="verse_gen_game_skeleton",
    category="Verse Helpers",
    description="Generate a full game manager device skeleton in Verse.",
    tags=["verse", "snippet", "game", "skeleton", "boilerplate"],
)
def run_gen_game_skeleton(device_name: str = "MyGameManager", **kwargs) -> dict:
    """
    Args:
        device_name: The Verse class name for the generated device.

    Returns:
        dict: {"status", "path", "device_name"}
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = _GAME_SKELETON.format(device_name=device_name, timestamp=timestamp)
    filename = f"{device_name}.verse"
    path = _write_snippet(filename, content, SUBCAT_GAME_SYSTEMS)
    _try_clipboard(content)
    log_info(f"Game skeleton generated → {path}")
    log_info(f"\n{'='*60}\n{content}\n{'='*60}")
    return {"status": "ok", "path": path, "device_name": device_name}


@register_tool(
    name="verse_gen_elimination_handler",
    category="Verse Helpers",
    description="Generate a Verse elimination event handler skeleton.",
    tags=["verse", "snippet", "elimination", "event", "kill"],
)
def run_gen_elimination_handler(**kwargs) -> dict:
    """Returns: dict: {"status", "path"}"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = f"# Generated {timestamp}\n" + _ELIMINATION_HANDLER
    path = _write_snippet("elimination_handler.verse", content, SUBCAT_GAME_SYSTEMS)
    _try_clipboard(content)
    log_info(f"Elimination handler generated → {path}")
    log_info(f"\n{'='*60}\n{content}\n{'='*60}")
    return {"status": "ok", "path": path}


@register_tool(
    name="verse_gen_scoring_tracker",
    category="Verse Helpers",
    description="Generate a Verse scoring tracker zone device skeleton.",
    tags=["verse", "snippet", "score", "tracker", "zone"],
)
def run_gen_scoring_tracker(max_score: int = 10, **kwargs) -> dict:
    """
    Args:
        max_score: The target score to win the round.

    Returns:
        dict: {"status", "path"}
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = f"# Generated {timestamp}\n" + _SCORING_TRACKER.format(max_score=max_score)
    path = _write_snippet("scoring_tracker.verse", content, SUBCAT_GAME_SYSTEMS)
    _try_clipboard(content)
    log_info(f"Scoring tracker generated → {path}")
    log_info(f"\n{'='*60}\n{content}\n{'='*60}")
    return {"status": "ok", "path": path}


@register_tool(
    name="verse_gen_prop_spawner",
    category="Verse Helpers",
    description="Generate a trigger-controlled prop spawn/despawn Verse skeleton.",
    tags=["verse", "snippet", "prop", "spawn", "trigger"],
)
def run_gen_prop_spawner(**kwargs) -> dict:
    """Returns: dict: {"status", "path"}"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = f"# Generated {timestamp}\n" + _PROP_SPAWN
    path = _write_snippet("prop_spawner_controller.verse", content, SUBCAT_DEVICE_WIRING)
    _try_clipboard(content)
    log_info(f"Prop spawner skeleton generated → {path}")
    log_info(f"\n{'='*60}\n{content}\n{'='*60}")
    return {"status": "ok", "path": path}
